In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [8]:
#creating datasets such as standardization is not required
from sklearn.datasets import make_classification
X,Y=make_classification(n_samples=100,n_features=10,n_classes=2,random_state=42)
X = pd.DataFrame(X)
Y

array([1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.30,random_state=42)

In [12]:
from sklearn.linear_model import LogisticRegression
l = LogisticRegression()
l.fit(X_train,Y_train)
y_pred = l.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1])

In [13]:
l.predict_proba(X_test)

array([[7.49632742e-01, 2.50367258e-01],
       [5.71492961e-02, 9.42850704e-01],
       [8.47383467e-03, 9.91526165e-01],
       [3.84386602e-02, 9.61561340e-01],
       [2.79853023e-02, 9.72014698e-01],
       [9.64640318e-01, 3.53596817e-02],
       [9.65369374e-01, 3.46306260e-02],
       [2.13024820e-01, 7.86975180e-01],
       [2.27546362e-01, 7.72453638e-01],
       [1.81401566e-01, 8.18598434e-01],
       [9.87298049e-01, 1.27019510e-02],
       [1.84390109e-03, 9.98156099e-01],
       [1.11638160e-03, 9.98883618e-01],
       [9.98846835e-01, 1.15316489e-03],
       [3.19528899e-03, 9.96804711e-01],
       [9.75335190e-01, 2.46648100e-02],
       [2.79003416e-02, 9.72099658e-01],
       [9.72840626e-01, 2.71593739e-02],
       [9.57717728e-01, 4.22822718e-02],
       [9.96764165e-01, 3.23583540e-03],
       [3.26255970e-02, 9.67374403e-01],
       [9.91543744e-01, 8.45625612e-03],
       [6.48321099e-01, 3.51678901e-01],
       [9.99581102e-01, 4.18898067e-04],
       [4.128605

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
s = accuracy_score(y_pred,Y_test)
c = confusion_matrix(y_pred,Y_test)
r = classification_report(y_pred,Y_test)
print(s)
print(c)
print(r)